[workspace]
resolver = "2"
members = [
    "structural-typing",
    "structural-typing-macros",
]

[workspace.package]
version = "0.2.0"
edition = "2024"
authors = ["Yoav Kaufman"]
license = "MIT OR Apache-2.0"
repository = "https://github.com/Crazytieguy/structural-typing-rs"

[workspace.dependencies]
structural-typing-macros = { path = "structural-typing-macros" }
syn = { version = "2", features = ["full", "extra-traits"] }
quote = "1"
proc-macro2 = "1"
